### ISSUE TITLE
Display readable and good structured relevant informations from blizzard cdn

### ISSUE THREAD

**Issue by ununseptium** [ununseptium/blizz-cdn-inspect#1]
This is going to be the first small task.

- [x] #3 Get the data from Blizzards CDN. (Probably WoW data only first)
- [x] #4 Create a meaningful and relevant output of this data. Not every part of a version file is going to be relevant.
- [x] #2 This includes that the web & templating part is already working.
